### ISSUE TITLE
Notifier adds an Unknown Method error on front-end entry form submissions

### ISSUE THREAD

**Issue by romainpoirier** [doublesecretagency/craft-notifier#16]
I have a front-end entry form where a notifier is set up.

The email notification is sent on save, but Notifier is blocking the Entry save because of this error:
```
Unknown Method – [yii\base\UnknownMethodException](https://www.yiiframework.com/doc-2.0/yii-base-unknownmethodexception.html)
Calling unknown method: craft\models\FieldLayout::getFields()
```

The content of the email is very simple (for test purpose), and is working:
`New forum submission: {{ entry.title }}`

If I disabled the notification, the Entry is saved as expected. So, unfortunately, the plugin is unusable.

Here's the stack trace:
```
2022-12-12 08:40:52 [web.ERROR] [yii\base\UnknownMethodException] yii\base\UnknownMethodException: Calling unknown method: craft\models\FieldLayout::getFields() in /vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /vendor/doublesecretagency/craft-notifier/src/models/EmailMessage.php(98): yii\base\Component->__call('getFields', Array)
#1 /vendor/doublesecretagency/craft-notifier/src/models/EmailMessage.php(58): doublesecretagency\notifier\models\EmailMessage->send(Object(craft\elements\User), Array)
#2 /vendor/doublesecretagency/craft-notifier/src/NotifierPlugin.php(201): doublesecretagency\notifier\models\EmailMessage->sendAll(Array)
#3 [internal function]: doublesecretagency\notifier\NotifierPlugin->doublesecretagency\notifier\{closure}(Object(craft\events\ModelEvent))
#4 /vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ModelEvent))
#5 /vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\elements\\...', 'afterSave', Object(craft\events\ModelEvent))
#6 /vendor/craftcms/cms/src/base/Element.php(4735): yii\base\Component->trigger('afterSave', Object(craft\events\ModelEvent))
#7 /vendor/craftcms/cms/src/elements/Entry.php(1958): craft\base\Element->afterSave(false)
#8 /vendor/craftcms/cms/src/services/Elements.php(2999): craft\elements\Entry->afterSave(false)
#9 /vendor/craftcms/cms/src/services/Elements.php(3247): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true, Array)
#10 /vendor/craftcms/cms/src/services/Elements.php(3024): craft\services\Elements->_propagateElement(Object(craft\elements\Entry), Array, 3, Object(craft\elements\Entry))
#11 /vendor/craftcms/cms/src/services/Elements.php(1039): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, true)
#12 /vendor/craftcms/cms/src/controllers/EntriesController.php(316): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#13 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#14 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#16 /vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-entry', Array)
#17 /vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('entries/save-en...', Array)
#18 /vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('entries/save-en...', Array)
#19 /vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /htdocs/index.php(12): yii\base\Application->run()
#22 {main} {"memory":35045088,"exception":"[object] (yii\\base\\UnknownMethodException(code: 0): Calling unknown method: craft\\models\\FieldLayout::getFields() at /vendor/yiisoft/yii2/base/Component.php:300)"} 
2022-12-12 08:40:52 [web.INFO] [application] Request context:
$_GET = [
    'p' => 'fr/pro/forum'
]
```

Versions:

- `"craftcms/cms": "4.3.4"`
- `"doublesecretagency/craft-notifier": "0.10.0"`

**Comment by lindseydiloreto** [comment]
Thanks for the heads up, this is now fixed in **v0.10.1**.

Looks like the Craft method `FieldLayout::getFields` was renamed to `FieldLayout::getCustomFields` in Craft 4. The old method wasn't deprecated, it was simply renamed.

Within the Notifier plugin, you only tripped over this line of code because it was attempting to send the same email twice to the same person. That's a totally normal thing to do, it should have (normally) just logged the duplicate and skipped sending a duplicate email. But because the Craft method was renamed, it threw an error instead.

Thanks again for reporting it! 🍺
